name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Build and Pack
      run: dotnet pack --configuration Release --output nupkgs

    - name: Publish to NuGet
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push $(PackageOutputPath)/$(PackageId).$(PackageVersion).nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
